image:
  file: .gitpod.Dockerfile
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
    
