image:
  file: .gitpod.Dockerfile
ports:
- port: 8080
  onOpen: open-preview
- port: 9002
  onOpen: ignore
tasks:
- name: Laravel
  init: cd $GITPOD_REPO_ROOT/laravel && composer install && php artisan key:generate --ansi
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
    
