image:
  file: .gitpod.Dockerfile
ports:
- port: 3306
  onOpen: ignore
- port: 8080
  onOpen: open-preview
- port: 9002
  onOpen: ignore
tasks:
- name: start up
  init: cd $GITPOD_REPO_ROOT/laravel && composer install
  command: >
    mysqld --daemonize &&
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
- init: echo 'init script' # runs during prebuild
  command: echo 'start script'
    
